sudo: false
language: node_js
cache: 
  - yarn
node_js:
  - "8.9"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - cd grpc && yarn
  - "node ./grpc/nodejs/server.js &"
script:
  - "node ./grpc/nodejs/client.js"
notifications:
  email:
    on_success: never
    on_failure: never
